### PR TITLE
implements proposed #129

### PR DESCRIPTION
**Pull request by DougAnderson444**
If you're ok with #129 this is the pull request to implement the feature. Very minor change that makes my async code work

### CODE REVIEW

**Comment by rosmcmahon** [comment]
this should not be required? you are adding an `await` to the return of an aync function that returns Promise<string>. 
AFAICT all this will do is change where try/catch would happen, right? there's no try/catch in this function, so why put an await there? can you explain further why this is necessary?

**Comment by hlolli** [comment]
Looks harmless to me, because it's calling 3rd party global function, and if await is present there at the front, will return fine for promises and non-promises. But what's really missing here, and that's perhaps another topic, is the lack of `typeof window.arweaveWallet.getActiveAddress === "function"` such check should be added, optionally in this PR, but not a blocker for this change imo.

**Comment by rosmcmahon** [comment]
here is a wallet that this was designed for, note that the function is already async: https://docs.th8ta.org/arconnect/functions#get-active-address

**Comment by hlolli** [comment]
> here is a wallet that this was designed for, note that the function is already async: https://docs.th8ta.org/arconnect/functions#get-active-address

that function returns a promise, but arweave-js is not treating it like such, which means it's broken in it's current state?

**Comment by rosmcmahon** [comment]
> > here is a wallet that this was designed for, note that the function is already async: https://docs.th8ta.org/arconnect/functions#get-active-address
> 
> that function returns a promise, but arweave-js is not treating it like such, which means it's broken in it's current state?

I don't see how. arweave-js' function return type is Promise<string> and that's what it returns, leaving the await to happen on the caller's side.

You can put the await before returning it, but the caller still needs to await regardless, and since arweave-js is not handling any possible error this also gets bubbled up to the caller. 

The only reason I've ever seen fit to use an await like this is when you are catching errors before returning to the caller. I guess I'm curious as to where this could possibly be making any difference in someone's code, which is why I'm banging on about it 😅

**Comment by DougAnderson444** [comment]
Hey guys, thanks for all your thoughts on this. 

I originally thought that this missing `await` was glitching up my code, but I think I found the "real" issue elsewhere (in my own wallet code), and I think Ros is right; If `getActiveAddress` returns a promise it does look like it's passed on to the caller to await for reolution. So there may be no need to modify this code after all

**Comment by rosmcmahon** [comment]
@DougAnderson444 I'd be interested to hear about your wallet.
Are you in the [Dev server](https://discord.gg/QuvfAWud)?

**Comment by DougAnderson444** [comment]
@rosmcmahon I am indeed, direct message sent over there

**Comment by rosmcmahon** [comment]
closing this PR. i found this article if anyone is interested and reading this, i think this explains the situation a little better than i have above [https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise](https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise)

**Pull request closed without merging**
