### PR TITLE
fix: access to window

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Comment by rosmcmahon** [comment]
hi, this PR is failing tests

**Comment by rosmcmahon** [comment]
Specifically, it's not building. You can see the failing runs above.

**Comment by Jack-Works** [comment]
> What is this PR attempting to fix? Not clear what the issue is

This library failed to run inside a Web Worker because there is no `window` variable in it.

**Comment by Jack-Works** [comment]
now i think it's ok

**Comment by rosmcmahon** [comment]
> > What is this PR attempting to fix? Not clear what the issue is
> 
> This library failed to run inside a Web Worker because there is no `window` variable in it.

IIRC there are other issues preventing this library from running inside web workers. Have you tested this PR locally?

**Comment by Jack-Works** [comment]
we have a patch to arweave-js https://github.com/DimensionDev/Maskbook/blob/develop/patches/arweave%401.11.4.patch to let it run in a Web Worker, but I didn't test all features. This PR just make it can be imported in a Web Worker without crash.

**Review by hlolli — APPROVED** [review]
I do approve of this, quite the homemade solution for an output wrapper, but it works. I've worked with workers and worklets and I can imagine this will fix issues related to that. Ops relate @rosmcmahon remember to squash-merge, alternatively, @Jack-Works could you maybe squash these commits into a 1 single commit?

**Comment by Jack-Works** [comment]
I prefer a squash-merge 👀

**Comment by rosmcmahon** [comment]
I presume someone tested this with ArConnect or arweave.app @hlolli ?

**Comment by hlolli** [comment]
backstory please to this type of testing @rosmcmahon ?

**Comment by hlolli** [comment]
typescript compiles global window vars to window. That's what typescript does, I see your concern in that regard.

**Comment by hlolli** [comment]
ts: location.path
js: window.location.path

**Comment by rosmcmahon** [comment]
yeah, i was thinking in more broad strokes actually:

- this PR is affecting the arweave window object. 
- the web wallets use that. 
- there's currently no integrated testing of web wallets

**Comment by rosmcmahon** [comment]
we should probably do a quick test before publishing a new release, or is a scream test ok? 😅

**Comment by Jack-Works** [comment]
Does that break something? "self" is equal to "window" in a normal Web page and also available as the global object in a Web Worker, I thought it should be ok?

**Comment by hlolli** [comment]
as long as we aren't releasing major version I think a scream test is ok. There's no regression, api change or behvioral change in this as far as I can see. If there's one, it's going to have to be a big surprise.

**Pull request merged**
