### PR TITLE
Remove unused debug function

### PR DESCRIPTION
**Pull request by hzhu**
It looks like there is an unused `debug` function in the `common` directory which is exported for both browser and Node.js environments. I'd like to propose removing function since it is is not used anywhere in the repository and potentially is problematic for frontend UI apps importing `arweave`.

The unused code can be problematic because it exports `inspect` from [`util`](https://www.npmjs.com/package/util) (a `Node.js` package) to web browser environments. Below are the results of importing `arweave` into a minimal [create-react-app](https://github.com/facebook/create-react-app):

Screen Shot 2021-12-25 at 7 42 40 PM

Related, `webpack` is unable to bundle browser apps that import `arweave`:

Screen Shot 2021-12-25 at 8 36 10 PM

### CODE REVIEW

**Comment by rosmcmahon** [comment]
TODO: manually run `npm run test:web` on this PR

**Comment by rosmcmahon** [comment]
@hzhu thanks for the PR! This is Xmas vacation time, but we'll take a look at this soon...

**Comment by hzhu** [comment]
`npm run test:web` looks good for this PR ✅ .

There are two _unrelated_ broken tests that exist on the `master` branch. Since they are unrelated to this PR, I've created https://github.com/ArweaveTeam/arweave-js/pull/122 to fix them.

**Comment by hzhu** [comment]
@rosmcmahon yeah let's wait until after the holidays and New Year's — Happy Holidays 🎄!

**Comment by rosmcmahon** [comment]
i think i found a way to fix this 'util' polyfill error without removing merkle.ts test code - _also!_ the merkle.ts module needs some work so it probably would be best not to remove it unless merkle.ts was stable, 

_and!_  I discovered a fix for this React error which is actually one very small change to package.json - one small change that probably should have been made long ago anyhow. 

i'll publish a new version, once I've updated a few other things, and then let me know if it's working for you, thanks for your help on this!

**Comment by rosmcmahon** [comment]
[i believe this is going to fix the issue](https://github.com/ArweaveTeam/arweave-js/pull/124/commits/0cfece2e68b97a652b681fe0fc16456cd440fbd6)

**Comment by rosmcmahon** [comment]
OK, my bad. I can actually no longer replicate the error using local lib on my machine ??? Will use your PR

**Comment by rosmcmahon** [comment]
this will be published ASAP

**Comment by rosmcmahon** [comment]
OK, so this still throws up an error about not finding 'util' for React, but your app will work. i presume you were also testing against your local folder with a node_modules folder that had a copy of the devDependencies: util also installed.
i think it might be best to go back to polyfilling this for the browser but with a dummy empty module as it's not actually needed

**Comment by rosmcmahon** [comment]
FYI, if you want to test for this, do the following:
```bash
git clone ...
npm i
npm run build
rm -r node_modules
```
something like that anyway

**Comment by hzhu** [comment]
@rosmcmahon thanks for looking into this!

Yeah it looks like the `util` package is used in other `common` code (besides `merkle.ts`) so the error still shows. Refactoring or polyfillling maybe the long term solution. For now, I can add `util` as a `devDependencies` which will rid the error. Appreciate your help!

**Comment by rosmcmahon** [comment]
I've moved 'util' from Dev to production dependencies now. Error should be gone in release arweave@1.10.22

**Pull request merged**
