### PR TITLE
feat: add method for getting a block by its height

### PR DESCRIPTION
**Pull request by rixcian**
I've added a new method for getting a block by its height. I've followed the official HTTP API documentation [here](https://docs.arweave.org/developers/server/http-api#get-block-by-height).

### CODE REVIEW

**Comment by rosmcmahon** [comment]
nice!

**Comment by rosmcmahon** [comment]
i'm having a bit of a problem with creating tags on your branch. will have to create another

**Comment by rosmcmahon** [comment]
your patch is live 😃
`arweave@1.14.4`

**Comment by rixcian** [comment]
Thanks @rosmcmahon, especially for the fast merge ❤️

**Pull request merged**
