### PR TITLE
Improve detect web crypto

### PR DESCRIPTION
**Pull request by septs**

### CODE REVIEW

**Comment by septs** [comment]
https://app.circleci.com/pipelines/github/DimensionDev/Maskbook/5157/workflows/c997a661-f5c2-4f1d-94c3-15fa8a01bfbe/jobs/15762/parallel-runs/0/steps/0-103

in maskbook build, server-side render
the runtime is not window object

**Comment by septs** [comment]
and use prettier formatted the file.

**Comment by septs** [comment]
@arweave-kyle

**Comment by Tedko** [comment]
@arweave-kyle  Thanks!

**Pull request merged**
