### PR TITLE
fix: fix error messages and comment typos

### PR DESCRIPTION
**Pull request by fuadop**
@rosmcmahon

### CODE REVIEW

**Comment by rosmcmahon** [comment]
hmm. i noticed that typo in the error message before, but was afraid to fix it in case error catching code was relying on it. having said that, they will just need to update their catch code when they update arweave-js, right? nothing permanent happening here.

**Comment by fuadop** [comment]
@rosmcmahon That's definitely true, didn't think about that. But yea, they would just change their error catching code.

**Comment by rosmcmahon** [comment]
i'll include this on the next release. and make it a minor to indicate this small change in output

**Comment by fuadop** [comment]
That's awesome @rosmcmahon . Yea it needs to be indicated 💪🏾

**Pull request merged**
