### PR TITLE
refactor: axios to fetch

### LINKED ISSUE #184: Manifest v3 compatibility
With the beginning of the next year, 2023, Google will only accept Chrome extensions following the Manifest v3. 
`Arweave-js` is used by most of the browser crypto wallets and I wonder if there are plans to make it somehow compliant with this new policy. 
As far as I know, it should mostly consist of replacing the `axios` HTTP client with some other that uses the native `fetch` mechanism as `XMLHttpRequest` won't be available.

### PR DESCRIPTION
**Pull request by martonlederer**
This pull request refactors the `arweave-js` codebase to use the `fetch` API instead of the `axios` module. This fixes the incompatibility with service workers and chrome extensions based on the Manifest v3 standard.

Closes #184

### CODE REVIEW

**Comment by martonlederer** [comment]
Status of this PR:
- Tests for the web bundle all pass, so it should work for the browser
- Nodejs version tests fail, the `Headers` class used by `fetch` is undefined and my solution to polyfill it does not work (polyfill code [here](https://github.com/ArweaveTeam/arweave-js/pull/192/commits/087d31509f0c0d1e0f52b72f1c168f79be142ec4#diff-966ecabf5f841a313ff2a3d7985efb9fe675f8cae063062dd8c5328c300ed448R7))

Any help is appreciated!

**Comment by martonlederer** [comment]
@rosmcmahon if you have a little bit of time to look at this, that would help massively as well

**Comment by martonlederer** [comment]
One possible solution could be to utilize the same technique that the crypto-driver uses in arweave-js, but I feel like this would be an overkill (?)

**Comment by rosmcmahon** [comment]
https://github.com/ArweaveTeam/arweave-js/blob/master/src/common/lib/api.ts#L46-L59

```ts
  public async get<T = any>(
    endpoint: string,
    config?: AxiosRequestConfig
  ): Promise<AxiosResponse<T>> {
    try {
      return await this.request().get<T>(endpoint, config);
    } catch (error: any) {
      if (error.response && error.response.status) {
        return error.response;
      }

      throw error;
    }
  }
```


ah. i didn't realise the purpose of the Axios error handling in this function before. it's making it like Fetch API: 

- just return http status codes without throwing an error. 
- only throw on connection errors. 

so there has been some work done in preparing arweave-js for conversion to fetch already...

**Comment by martonlederer** [comment]
Yeah exactly, that's what I realized too. Altho this could have been done more easily, with [validateStatus](https://github.com/axios/axios#handling-errors).

**Comment by rosmcmahon** [comment]
i'm looking at raising the minimum node.js version to 16 and using the new built-in Fetch API

**Comment by martonlederer** [comment]
> i'm looking at raising the minimum node.js version to 16 and using the new built-in Fetch API

Would be the easiest solution. Do you think it would cause mayor incompatibilities? LTS is `18.12.1` right now, so i think it would be fine.

**Comment by rosmcmahon** [comment]
hey @martonlederer can i get push access to your repo?

**Comment by martonlederer** [comment]
@rosmcmahon you should be invited now

**Comment by rosmcmahon** [comment]
no Windows laptop handy. troubleshooting through github actions 😃

**Comment by rosmcmahon** [comment]
all tests passing...

**Comment by rosmcmahon** [comment]
thoughts about using nodejs Fetch API:

- it's marked experimental, I have already seen some typing changes while using it over the last couple of months, we will need to keep an eye on it for changes, but this is not a big deal i think. builds break, you fix them.
- if someone wants to use nodejs < 16 they can install a previous version of arwaeve-js

**Comment by rosmcmahon** [comment]
i'm not gonna publish this straight away. maybe another set of eyes first, and then update the minor version. 

can you be the extra set of eyes @hlolli ?

**Comment by rosmcmahon** [comment]
yeah, great work @martonlederer !! thanks for taking the time on this important PR! 😃

**Pull request merged**
